export const CONTEXT_OPEN_SELECTOR = 1;
export const CONTEXT_CLOSE_SELECTOR = 2;
export const CONTEXT_OPEN_DECLARATION = 4;
export const CONTEXT_CLOSE_DECLARATION = 8;
export const CONTEXT_OPEN_ATTRIBUTE_NAME = 16;
export const CONTEXT_CLOSE_ATTRIBUTE_NAME = 32;
export const CONTEXT_OPEN_ATTRIBUTE_VALUE = 64;
export const CONTEXT_CLOSE_ATTRIBUTE_VALUE = 128;
export const CONTEXT_OPEN_DECLARATION_BODY = 256;
export const CONTEXT_CLOSE_DECLARATION_BODY = 512;
export const CONTEXT_OPEN_COMMENT = 1024;
export const CONTEXT_CLOSE_COMMENT = 2048;
export const CONTEXT_OPEN_COMMENT_CONTENT = 4096;
export const CONTEXT_CLOSE_COMMENT_CONTENT = 8192;

export const NODETYPE_DECL = 1;
export const NODETYPE_COMMENT = 2;
export const NODETYPE_ATTRIBUTE = 4;
